name: 'Core'
version: 1.9.2
main: chasingclub.server.core.Core
api-version: 1.19
author: ItDragClick
authors:
  - Pinont
description: Plugin for main server ChasingClub
depend:
  - Vanish
  - PlaceholderAPI

commands:
  setspawn:
    description: set the spawn
    usage: /setspawn

  invslot:
    description: invslot command
    usage: /invslot

  f:
    description: ffffff
    usage: /f

  fade:
    description: test command
    usage: /fade

  ping:
    description: ping command
    usage: /ping
    aliases:
      - howmuchping
      - tfping
      - wtfping

  enderchest:
    description: enderchest
    usage: /enderchest
    aliases:
      - enderchest
      - ec
      - ender_chest

  core:
    description: core
    usage: /core

  spawn:
    description: go to spawn
    usage: /spawn

  sudo:
    description: sudo player
    usage: /sudo

  map:
    description: map enable/disable
    usage: /map

  crash:
    description: crash player
    usage: /crash

  kaboom:
    description: kaboom player
    usage: /kaboom

  givekit:
    description: givekit player
    usage: /givekit

  setkit:
    description: setkit player
    usage: /setkit

  duel:
    description: duel player
    usage: /duel

  fly:
    description: fly a player
    usage: /fly
    aliases: [fly, flight]

  b:
    description: enable/disable build mode
    usage: /build
    aliases: [b, build]

  gms:
    description: set gamemode 0
    usage: /gms

  gmc:
    description: set gamemode 1
    usage: /gmc

  gma:
    description: set gamemode 2
    usage: /gma

  gmsp:
    description: set gamemode 3
    usage: /gmsp

  feed:
    description: feed player
    usage: /feed

  heal:
    description: heal player
    usage: /heal

  fling:
    description: fling player
    usage: /fling

  getkit:
    description: kit
    usage: /getkit

  warden:
    description: start warden chase game
    usage: /warden

  earape:
    description: earape player
    usage: /earape

permissions:
  ranks.admin:
    description: "admin"
    children: [ranks.mod, ranks.jrmod] #idk if it inerhits children from lower children, if so you can remove ranks.jrmod
  ranks.mod:
    description: "mod"
    children: [ranks.jrmod]
  ranks.jrmod:
    description: "jrmod"