name: SMPCore
version: '${project.version}'
main: cc.core.Core
api-version: 1.19
authors: [ Pinont ]
description: ChasingClub SMP Core

commands:
  rtp:
    description: random Teleport

  spawn:
    description: Spawn

  team:
    description: Team

  bed:
    description: Bed

  pvp:
    description: PvP