name: SMPCore
version: '${project.version}'
main: cc.core.Core
api-version: 1.19
authors: [ Pinont ]
description: ChasingClub SMP Core

commands:
  rtp:
    description: random Teleport

  spawn:
    description: Beck to server spawn

  team:
    description: Team up with friends

  bed:
    description: Go back to your bed

  pvp:
    description: toggle pvp off/on

  srcTake:
    description: get secret item that been developing

  setHealth:
    description: set health of player