name: SMPCore
version: '${project.version}'
main: cc.core.Core
api-version: 1.19
authors: [ Pinont ]
description: ChasingClub SMP Core

commands:
  rtp:
    description: random Teleport
    usage: /rtp

  spawn:
    description: Spawn
    usage: /spawn

  team:
    description: Team
    usage: /team

  bed:
    description: Bed
    usage: /bed

  pvp:
    description: PvP
    usage: /pvp